# @package _group_
kind: directory
outdir: samples
key_order:
  - image
  - depth
  - predicted_image
  - predicted_depth
  - discr_output_fake
  - discr_output_real
  - inpainted
  - inpainted_depth
rescale_keys:
  - discr_output_fake
  - discr_output_real
last_without_mask: False
