generator_kind: disocclusion

mask_generator_kwargs:
  irregular_kwargs:
    min_times: 1
    max_times: 5
    max_width: 500
    max_angle: 4
    max_len: 200

  box_kwargs:
    margin: 10
    bbox_min_size: 84
    bbox_max_size: 421
    max_times: 6
    min_times: 1

max_masks_per_image: 1

cropping:
  out_min_size: 720
  handle_small_mode: upscale
  out_square_crop: False
  crop_min_overlap: 1

max_tamper_area: 0.5
